"""initial

Revision ID: ed5c3656796e
Revises: 
Create Date: 2026-02-22 00:05:37.358558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed5c3656796e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicios_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=100), nullable=False),
    sa.Column('equipamento', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_por_sistema', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PERSONAL', 'ALUNO', name='role'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('alunos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('personais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('conjuntos_treino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vinculos_personal_aluno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('personal_id', sa.UUID(), nullable=False),
    sa.Column('inicio_em', sa.DateTime(), nullable=False),
    sa.Column('fim_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['personal_id'], ['personais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'ativo', name='uq_aluno_vinculo_ativo')
    )
    op.create_table('treinos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conjunto_treino_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('observacoes_aluno', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conjunto_treino_id'], ['conjuntos_treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercicios_treino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('treino_id', sa.UUID(), nullable=False),
    sa.Column('exercicio_base_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('numero_series_prescritas', sa.Integer(), nullable=False),
    sa.Column('prescricao', sa.Text(), nullable=True),
    sa.Column('repeticao_ou_tempo', sa.String(length=50), nullable=True),
    sa.Column('rer_rm_valor', sa.String(length=50), nullable=True),
    sa.Column('descanso_segundos', sa.Integer(), nullable=True),
    sa.Column('tecnica', sa.Enum('PADRAO', 'ISOMETRIA', 'INSTABILIDADE', name='tecnica'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('observacoes_aluno', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercicio_base_id'], ['exercicios_base.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessoes_treino',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('treino_id', sa.UUID(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('EM_ANDAMENTO', 'FINALIZADO', name='statussessao'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['treino_id'], ['treinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_executadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sessao_treino_id', sa.UUID(), nullable=False),
    sa.Column('exercicio_treino_id', sa.UUID(), nullable=False),
    sa.Column('numero_serie', sa.Integer(), nullable=False),
    sa.Column('peso_utilizado', sa.Float(), nullable=True),
    sa.Column('repeticoes_realizadas', sa.Integer(), nullable=True),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercicio_treino_id'], ['exercicios_treino.id'], ),
    sa.ForeignKeyConstraint(['sessao_treino_id'], ['sessoes_treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_executadas')
    op.drop_table('sessoes_treino')
    op.drop_table('exercicios_treino')
    op.drop_table('treinos')
    op.drop_table('vinculos_personal_aluno')
    op.drop_table('conjuntos_treino')
    op.drop_table('personais')
    op.drop_table('alunos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('exercicios_base')
    # ### end Alembic commands ###
